
site_name: 편한 위키
theme:
  name: material
  logo: images/logo-pyeonhanwiki-final.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
  font:
    text: Noto Sans KR
    code: Fira Code
nav:
  - 개요: index.md
  - 구단 디자인:
      - 유니폼: 구단디자인/유니폼/유니폼.md
  - 역사: 역사/역사.md
  - 팀 컬러: 팀컬러/팀컬러.md
  - 상세: 상세/상세.md
  - 현역 임원진: 
      - 개요: 현역임원진/개요/현역임원진.md
      - 감독: 현역임원진/감독/감독.md
      - 주장: 현역임원진/주장/주장.md
      - 총무: 현역임원진/총무/총무.md
  - 현역 선수단: 
      - 현역 선수진: 현역선수단/현역선수진/현역선수진.md
      - 감독: 현역선수단/감독/감독.md
      - 선수: 
          - 김찬수: 현역선수단/선수/현역/김찬수.md
  - 타 구단과의 관계:
      - Pirates: 타 구단과의 관계/Pirates.md
  - 역대 선수 및 인물:
      - 영구 결번: 역대 선수 및 인물/영구 결번/영구결번.md
      - 역대 감독: 역대 선수 및 인물/역대 감독/감독.md
      - 역대 주장: 역대 선수 및 인물/역대 주장/주장.md
      - 역대 총무: 역대 선수 및 인물/역대 총무/총무.md
      - 역대 임원진: 역대 선수 및 인물/역대 임원진/임원진.md
      - 역대 선수단 및 등번호: 역대 선수 및 인물/역대 선수단 및 등번호/역대선수단.md
  - 역대 기록:
      - 공식 리그 성적:
          - 2024하반기드림리그:
              - 경기일정: 
                  - 20240727-0830: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20240727-0830/결과.md
                  - 20240810-0830: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20240810-0830/결과.md
                  - 20240824-0830: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20240824-0830/결과.md
                  - 20240831-1730: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20240831-1730/결과.md
                  - 20240907-0830: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20240907-0830/결과.md
                  - 20241005-0830: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20241005-0830/결과.md
                  - 20241012-1100: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20241012-1100/결과.md
                  - 20241019-1730: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20241019-1730/결과.md
                  - 20241102-0800: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20241102-0800/결과.md
                  - 20241116-0800: 역대 기록/공식 리그 성적/2024하반기드림리그/경기일정/20241116-0800/결과.md
              - 구단성적: 역대 기록/공식 리그 성적/2024하반기드림리그/구단 성적/구단성적.md
              - 상대전적: 역대 기록/공식 리그 성적/2024하반기드림리그/상대 전적/상대전적.md
          - 포스트 시즌 전적: 역대 기록/공식 리그 성적/2024하반기드림리그/포스트 시즌 전적/포스트시즌.md
      - 개인 성적:
          - 통산: 역대 기록/개인 성적/통산/통산.md
          - 단일 시즌: 역대 기록/개인 성적/단일시즌/단일시즌.md
      - 타이틀 홀더:
          - 타자: 역대 기록/타이틀 홀더/타자/타자.md
          - 투수: 역대 기록/타이틀 홀더/투수/투수.md
          - MVP 및 신인왕: 역대 기록/타이틀 홀더/MVP 및 신인왕/MVP신인왕.md
      - 시즌별 팀 내 최고기록
          - 2024 하반기 드림리그: 역대 기록/시즌별 팀 내 최고기록/2024하반기드림리그/결과.md
  - 캐치프레이즈: 캐치프레이즈/캐치프레이즈.md
  - 논란 및 사건 사고: 논란 및 사건 사고/논란사건.md
  - 이야깃거리: 이야깃거리/이야기.md

